[tool.poetry]
name = "prbot-telegram"
version = "0.1.0"
description = ""
authors = ["rg.batyrshin <rg.batyrshin@localhost>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^3.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
